name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ github.token }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
